# Numpy
NumPy is the fundamental package for scientific computing with Python. It contains among other things:

* a powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined and this allows NumPy to seamlessly and speedily integrate with a wide variety of projects.

Code adapted from :
- Nicolas P. Rougier, . (2015, August 21). numpy-tutorial: Version 1.0 (Version 1.0). Zenodo. http://doi.org/10.5281/zenodo.28817 (https://github.com/rougier/numpy-tutorial All code and material is licensed under a Creative Commons Attribution-ShareAlike 4.0.)
- Nicolas P. Rougier, ., Jessica B. Hamrick, ., ibah, ., Gavin Heverly-Coulson, ., Dapid, ., Christoph Deil, ., & Bartosz Telenczuk, . (2016, August 27). numpy-100: Version 1.1 (Version 1.1). Zenodo. http://doi.org/10.5281/zenodo.61020 (https://github.com/rougier/numpy-100 All code and material is licensed under MIT license)
- https://github.com/ksopyla/numpy-tutorial/ All code and material is licensed under MIT license. Copyright (c) 2017 Krzysztof Sopyła

Resources:
- https://numpy.org/doc/stable/user/
- https://www.labri.fr/perso/nrougier/from-python-to-numpy/


## Creating array

In [ ]:
import numpy as np

In [ ]:
# create 1D array
a = np.array([1, 2, 3])  # Create a dimension 1 array
print(type(a))          # Prints "<type 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)" b/c it is a vector of 3 elements
print(a[0], a[1], a[2])   # Prints "1 2 3"

In [ ]:
# create 2D array
b = np.array([[1,2,3],[4,5,6]])   # Create a 2X3 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])  # Prints "1 2 4"

In [ ]:
# create different 2D arrays
a = np.zeros((2,2))  # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                     #          [ 0.  0.]]"

b = np.ones((1,2))   # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


d = np.eye(2)        # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                     #          [ 0.  1.]]"

e = np.random.random((2,2)) # Create an array filled with random values
print (e)                     # Might print "[[ 0.91940167  0.08143941]
                            #               [ 0.68744134  0.87236687]]"

# Create an array filled with range values
# Start and stop indicate range values
# Step indicates the numerical distance between values.
# the code above is the same as np.arange(15).reshape(3, 5)
f = np.arange(start=1, stop= 16, step=1).reshape(3, 5)

print(f)


## Numpy dtype

- int: `int8`, `int16`, `int32`, `int64`
- uint(non-negative only): `uint8` (image) ~ `uint64`  
- float: `float16`, `float32` (standard), `float64`(default)
- complex: `complex64`, `complex128`
- boolean: `bool_`
- etc: `str_`, `bytes_`, `object_`

In [ ]:
# array datatype
x = np.array([1, 2])  # Let numpy choose the datatype
print (x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])  # Let numpy choose the datatype
print (x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print (x.dtype)

## Indexing array

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)
print (a[0, 1])   # Prints "2"

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

In [ ]:
# A slice of an array is a view into the same data, so modifying it will modify the original array.
print (a[0, 1])   # Prints "2"
a[0,1] = 77       # Change 2 to 77
print (a[0, 1])   # Prints "77"
print(a)

In [ ]:
# Remember, b refers to a. Changing b will change a too.
print (a[0, 1])
b[0, 0] = 2      # Change 77 to 2; b[0, 0] is the same piece of data as a[0, 1]
print (a[0, 1])  # Now changes back to 2

In [ ]:
# If you don't want this, please copy your array!
print (a[0, 1])
c = a[:2, 1:3].copy()
c[0,0] =77 # this only changes c, not a
print(a[0,1])


In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print (row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"


In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)  # Prints "[[ 2]
                            #          [ 6]
                            #          [10]] (3, 1)"


In [ ]:
#Integer array indexing:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print (a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# Using np.arange() to create an array of indices
print(a[np.arange(3), [0, 1, 0]])  # Prints "[1     4 5]"

In [ ]:
# The above example of integer array indexing is equivalent to this:
print (np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

In [ ]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print (a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print (np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

In [ ]:
#Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print (bool_idx)      # Prints "[[False False]
                    #          [ True  True]
                    #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print (a[bool_idx])  # Prints "[3 4 5 6]"


In [ ]:
# We can do all of the above in a single concise statement:
print (a[a > 2])     # Prints "[3 4 5 6]"

## Shaping & modifying matrix

In [ ]:
# combining array
a = np.array([[1,5,9], [2,6,10]])
b = np.array([[3,7,11], [4,8,12]])

# Stack two arrays row-wise
print(np.vstack((a,b)))

# vstack is the same as concatenate arrays along the axis 0 (row)
print(np.concatenate((a,b), axis=0))

In [ ]:
# Stack two arrays column-wise
print(np.hstack((a,b)))

# hstack is the same as concatenate arrays along the axis 1 (column)
print(np.concatenate((a,b), axis=1))

In [ ]:
# flatten
a = np.array([[1,2], [3,4]])
a = a.flatten()
print(a)

In [ ]:
# reshape
a = np.array([[1,2], [3,4]])
a = a.reshape((4,)) # make it as vector
print(a)

In [ ]:
# reshape
a = np.array([1,5,9, 2,6,10]) #originally vector
print(a)
a = a.reshape((3,2)) # make it 3*2
print(a)

In [ ]:
# add new axis
x = np.array([1, 2]) # shape (2,)
print(x)
y = np.expand_dims(x, axis=0) # add new axis row-wise (shape becomes 1*2) =  x[np.newaxis, :]
print(y)
z = np.expand_dims(x, axis=1) # add new axis column-wise (shape becomes 2*1)  x[:, np.newaxis]
print(z)

## Matrix computation

In [ ]:
#basic math operation
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print (x + y)
print (np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print (x - y)
print (np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print (x * y)
print (np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print (x / y)
print (np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print (np.sqrt(x))

# Summation
print (np.sum(x))  # Compute sum of all elements; prints "10"
print (np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

In [ ]:
#vector matrix operation
v = np.array([9,10])
w = np.array([11, 12])

x = np.array([[1,2],[3,4]])
# this is
# [[1,2]
# [3,4]]

y = np.array([[5,6],[7,8]])
# this is
# [[5,6]
# [7,8]]

# Inner product of vectors; both produce 219
print (v.dot(w))
print (np.dot(v, w))



In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print (x.dot(v))
print (np.dot(x, v))


In [ ]:
# Matrix / matrix product; both produce the rank 2 array = matrix multiplication
# but using np.matmul or a @ b is preferred.
# [[19 22]
#  [43 50]]
print (x.dot(y))
print (np.dot(x, y))
print(np.matmul(x, y))
print(x @ y)

# cf. elementwise mutiplication
print(x*y)

In [ ]:
# Transpose
x = np.array([[1,2], [3,4]])
print (x)    # Prints "[[1 2]
           #          [3 4]]"
print (x.T)  # Prints "[[1 3]
           #          [2 4]]"


In [ ]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print (v)    # Prints "[1 2 3]"
print (v.T)  # Prints "[1 2 3]"

## Array broadcasting

You want to add the vector v = [1,0,1] to each row of the matrix x and save to y

In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
v = np.array([1, 0, 1])

There can be several ways to to do this...

In [ ]:
#1. solve by using array indexing
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(3):
    y[i, :] = x[i, :] + v

print (y)

In [ ]:
#2. solve by np.tile
vv = np.tile(v, (3, 1))  # Stack v in a shape of (4,1); 4 copies of v on top of each other
print (vv)                 # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]

y = x + vv  # Add x and vv elementwise
print (y)

But this is much *simpler* way! Use array broadcasting

In [ ]:
#2. solve by broadcasting
y = x + v  # Add v to each row of x using broadcasting
print (y)

In [ ]:
# if you want to add a vector to each column of a matrix, not row
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print ((x.T + v).T)

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print (x * 2)

## Miscellenous

### Generate random numbers

In [ ]:
# generate random integer
print(np.random.randint(10)) #output a random integer between 0 and 10
# generate random floats
print(np.random.rand()) # output a random float between 0 and 1
# generate a random value based on an array of values.
print(np.random.choice([3, 5, 7, 9]))

# generate random integer in matrix
print(np.random.randint(10, size=(2,2))) #output a random integer between 0 and 10  in 2x2 matrix
# generate random floats  in matrix
print(np.random.rand(2,2)) # output a random float between 0 and 1  in 2x2 matrix
# generate a random value based on an array of values in matrix
print(np.random.choice([3, 5, 7, 9], size=(2,2)))

### Finding & Filtering arrays

In [ ]:
#You can search an array for a certain value, and return the indexes that get a match.
arr = np.array([1, 2, 3, 4, 5, 4, 4])
positions = np.where(arr == 4)
print(positions)

In [ ]:
arr = np.array([[1, 6, 3],
              [8, 2, 5]])
positions = np.where(arr > 4)
print(positions)


In [ ]:
# min and max
x = np.array([3, 7, 2, 9, 5])

i_min = np.argmin(x)
i_max = np.argmax(x)

print("x:", x)
print("argmin index:", i_min, "value:", x[i_min])
print("argmax index:", i_max, "value:", x[i_max])

### NaN type (Not a Number)

In [ ]:
# nan is undefined number
print(0 * np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan + np.nan)


In [ ]:
# Always use np.isnan(x) to check if x is nan!
print(np.nan == np.nan)
print(np.nan is np.nan)
print(np.float64('nan') is np.float64('nan') )
print(np.nan in set([np.nan]))

In [ ]:
# cf. python None (null value)
print(None is None) # recommended
print(None == None)

# Pandas

So far, we have learned how to handle different data types such as lists, dictionaries, and NumPy arrays. However, real-world data is rarely this simple or clean. It often comes in messy, complex formats and requires additional steps such as cleaning, filtering, and transforming.

Pandas provides many useful features for this kind of **preprocessing**. It allows you to work with data in a table-like format, making it easier to organize, manipulate, and analyze structured data.


Tutorials are adapted from:
* https://github.com/remayer/WS19_Python_for_PsychologistsBSD 3-Clause License/ Copyright (c) 2019, remayer/dominikkraft. All rights reserved.
* https://github.com/guipsamora/pandas_exercises under BSD 3-Clause License. Copyright (c) 2018, Guilherme Samora. All rights reserved.

More resources:
* https://github.com/justmarkham/pandas-videos


## Create Dataframe

Pandas has two basic data structure: ***series* and *dataframe***. A series is just a single column data, and multiple series (multiple columns) makes a dataframe.

In [ ]:
# these s1 and s2 are series
s1 = pd.Series([3,4,7,8,4,1], name="apples")
s2 = pd.Series([5,9,12,2,9,-99], name="bananas")

print(s1)
print(s2)

In [ ]:
# indexing works similar to list
s2[5] # get value at the fifth position of s2

In [ ]:
# create dataframe from these series data
fruits= {"apples" : s1, "bananas" : s2} # first we need to arrange our series in a dictionary
shoppinglist = pd.DataFrame(fruits) # pd.Dataframe(data) conveniently builds a nice looking dataframe for us

shoppinglist.head(3) # show first 3 rows in our shoppinglist

In [ ]:
# another way to combine two series is to use pd.concat with axis=1 (concatenate along the columns, not rows)
shoppinglist = pd.concat([s1,s2], axis=1)
shoppinglist.tail(3) # show last 3 rows in our shoppinglist

## Change row index and column names

As you can see, when you create a dataframe, we have integer numbers on the leftmost column as a default and this denotes the indices of each row. You can customize these indices using `.set_index`. If you want to modify the column names then use `.rename`.

In [ ]:
# if you want to set customer names who bought fruits as row indicies
customer=["Victoria", "Rhonda", "Elli", "Rebecca", "Lucie", "Isa"]
shoppinglist = shoppinglist.set_index([customer])
shoppinglist

In [ ]:
# if you want to rename index Victoria to Biance
shoppinglist.rename(index = {"Victoria":"Bianca"}, inplace=True)
shoppinglist

In [ ]:
# If you want to change column names, just give dictionary of how the names sholud be changed
shoppinglist.rename(columns={'apples': 'pineapples', 'bananas': 'lemons'}, inplace=True)
shoppinglist

In [ ]:
# Or you can just reset the column names
shoppinglist.columns = ['apples', 'bananas']
shoppinglist

## Add and drop columns and rows

In [ ]:
# if you want to add another column 'plum' to your dataframe
shoppinglist["plums"]= [1,2,3,4,5,6]
shoppinglist

In [ ]:
# if you want to insert a new column to specific location
shoppinglist.insert(2, "oranges", [1,2,3,4,5,6]) # new col will be inserted into the third column
shoppinglist

In [ ]:
# For adding a row, you first need to create a dataframe with a new row and append it to existing one.
norbert = pd.DataFrame([[5,5,-99,4]], columns=shoppinglist.columns.tolist()) ## list(old_dataframe) works also!
shoppinglist = shoppinglist.append(norbert)
# don't forget to update your row index accordinly
customer=["Bianca", "Rhonda", "Elli", "Rebecca", "Lucie", "Isa", "Norbert"]
shoppinglist = shoppinglist.set_index([customer])
shoppinglist

In [ ]:
# or you can use pd.concat over rows (axis=0 is default)
james = pd.DataFrame([[1,2,3,4]], columns=shoppinglist.columns.tolist()) ## list(old_dataframe) works also!
shoppinglist = pd.concat([shoppinglist, james])
customer=["Bianca", "Rhonda", "Elli", "Rebecca", "Lucie", "Isa", "Norbert", "James"]
shoppinglist = shoppinglist.set_index([customer])
shoppinglist

In [ ]:
# to drop your Bianca row
shoppinglist = shoppinglist.drop(index=["Bianca"])
shoppinglist

In [ ]:
# to drop your plums columns
shoppinglist = shoppinglist.drop(columns=["plums"])
shoppinglist

## Indexing

In [ ]:
# access columns by their names (use list)
shoppinglist[["apples", "bananas"]]

Try to only show what one customer bought at the Wochenmarkt using "str-slicing":


In [ ]:
# access rows by their names (using slicing)
shoppinglist["Rhonda":"Elli"]

In [ ]:
# you can also access rows by integer slicing
shoppinglist[0:2]

In [ ]:
# access both rows and columns using dataframe.loc[row_selection,column_selection]
shoppinglist.loc[["Isa","Elli","Norbert"], ["bananas", "oranges"]]

In [ ]:
# or you can also access both rows and columns using integer numbers using .iloc itead of .loc
shoppinglist.iloc[[0,1],[0,1]] # access first two rows and columns;  same as shoppinglist.iloc[0:2,0:2]

## Filtering & Sorting

Some of you might have noticed that our data has some negative consumption values (-99) which do not make sense! In practice, -99 often denotes the missing values. Let's find where the missing value locates using boolean filtering.

In [ ]:
# get boolean indexing of negatvie values in the column bananas
cond = shoppinglist["bananas"] <0
print(cond)

In [ ]:
# using this boolean index for selecting the relevant rows.
shoppinglist.loc[cond]

In [ ]:
# You can also combine two or more conditional statements
cond = (shoppinglist["bananas"] < 0) | (shoppinglist["oranges"] < 0) # | denotes OR operation, and & denotes AND
shoppinglist.loc[cond]

In [ ]:
# Replace -99 with np.nan (not a number values), so that they can be ignored in later analysis
shoppinglist = shoppinglist.replace(-99, np.nan)

In [ ]:
# sort values by specific column (default is increasing order; ascending = True)
shoppinglist.sort_values(by = "oranges", ascending = False) #decreasing

## Transform data
Sometimes you want to transform the data into different units and format. In such case, you can use `.apply()`. It's very similar to filter method you learned from numpy tutorial.

In [ ]:
# if you want to categorize people into two groups based on how many bananas they bought
def more_than_five(x):
    if x > 5:
        return 'A'
    else:
        return 'B'

shoppinglist['bananas'].apply(more_than_five)

In [ ]:
# you can insert this resulted series into new column 'type'
shoppinglist['type'] = shoppinglist['bananas'].apply(more_than_five)
shoppinglist

In [ ]:
# you can also use lambda function
double = lambda x: x*2
shoppinglist['bananas'].apply(double) #double the banana consumption

## Descriptive Statistics
Pandas offers various methods to get an overview of your data e.g., mean, count, sum etc

In [ ]:
# first of all, you can get the summarized data using .describe
shoppinglist.describe()
# note we have 6 entries for both banana and orange columns since we have one NA for each

In [ ]:
# you can calculate how many A and B customer types are there
shoppinglist['type'].value_counts()

In [ ]:
# to get min/max number of banana consumption
minb = shoppinglist['bananas'].min()
maxb = shoppinglist['bananas'].max()
print('min is {} and max is {}'.format(minb, maxb))

In [ ]:
# to get mean/median/sum value of banana consumpton
mean = shoppinglist['bananas'].mean()
median = shoppinglist['bananas'].median()
summ = shoppinglist['bananas'].sum()

print('mean is {} and median is {} and sum is {}'.format(mean, median, summ))

## Grouping
Imagine you are interested how fruit comsumptions are different depending on the customer's type A and B. You can group the data easily using `.groupby()`

In [ ]:
# get average fruit consumptions for type A and B
shoppinglist.groupby('type').mean()

In [ ]:
# get count/mean/sum fruit consumptions for type A and B
shoppinglist.groupby('type').agg(['count', 'mean', 'sum'])

## Visualization
Pandas even provide a simple visualzation tool for exploring data!

In [ ]:
# create the plot
shoppinglist.plot(kind='bar')

# Set the title and labels
plt.xlabel('Customers')
plt.ylabel('Fruit Consumed')
plt.title('Fruit Consumption')

# show the plot
plt.show()

In [ ]:
shoppinglist.bananas.plot(kind='hist')

In [ ]:
shoppinglist.type.value_counts().plot(kind='bar')

## Other useful features that Pandas provides
* .merge, .join, .concat: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html
* .str : https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html
* pivot table: https://pandas.pydata.org/pandas-docs/stable/user_guide/reshaping.html
* `pandas_profiling` is the package that help profiling pandas dataframe